name: CI
on: [pull_request, push]
env:
  CI: true

jobs:
  test:
    name: Tests for Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ["4", "6", "8", "10", "12", "14", "16", "18", "20"]
        os: [ubuntu-latest, windows-latest, macos-13]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm test
